version: "3"

services:
  consul1:
    hostname: consul1
    image: consul
    command: consul agent -server -ui -config-dir=/consul/config
    volumes:
      - ./consul-srv-config/consul:/consul/config
    networks:
      app_net:
    expose:
      - "8300"
      - "8300/udp"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
    ports:
      - "8500"
  consul2:
    hostname: consul2
    image: consul
    command: consul agent -server -ui -config-dir=/consul/config
    volumes:
      - ./consul-srv-config/consul:/consul/config
    networks:
      app_net:
    expose:
      - "8300"
      - "8300/udp"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
    ports:
      - "8500"
  consul3:
    hostname: consul3
    image: consul
    command: consul agent -server -ui -config-dir=/consul/config
    volumes:
      - ./consul-srv-config/consul:/consul/config
    networks:
      app_net:
    expose:
      - "8300"
      - "8300/udp"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
    ports:
      - "8500"
  app:
    volumes:
      - ./consul-app-config/consul:/consul/config
    image: tramasoli/consul-demo-client:app
    networks:
      - app_net
    ports:
      - "8080"
  nginx:
    volumes:
      - ./consul-nginx-config/consul-template:/consul-template
      - ./consul-nginx-config/consul:/consul/config
      - ./consul-nginx-config/nginx/nginx.conf:/etc/nginx/nginx.conf
    image: tramasoli/consul-demo-client:nginx
    networks:
      - app_net
    ports:
      - "80"
networks:
  app_net:
