version: '2'

services:
  consul1:
    hostname: consul1
    image: consul
    dns: 172.18.233.1
    command: consul agent -server -ui -config-dir=/consul/config
    volumes:
      - ./consul-srv-config:/consul/config
    networks:
      app_net:
        ipv4_address: 172.18.233.20
    expose:
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
  consul2:
    hostname: consul2
    image: consul
    dns: 172.18.233.1
    command: consul agent -server -ui -config-dir=/consul/config
    volumes:
      - ./consul-srv-config:/consul/config
    networks:
      app_net:
        ipv4_address: 172.18.233.21
    expose:
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
  consul3:
    hostname: consul3
    image: consul
    dns: 172.18.233.1
    command: consul agent -server -ui -config-dir=/consul/config
    volumes:
      - ./consul-srv-config:/consul/config
    networks:
      app_net:
        ipv4_address: 172.18.233.22
    expose:
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8500"
      - "8600"
      - "8600/udp"
  app1:
    volumes:
      - ./consul-app-config:/consul/config
    image: tramasoli/consul-demo-client
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.233.0/24
          gateway: 172.18.233.1
          ip_range: 172.18.233.64/26
